@HotelListing_API_HostAddress = http://localhost:5084

GET {{HotelListing_API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{HotelListing_API_HostAddress}}/api/hotel

###


POST {{HotelListing_API_HostAddress}}/api/hotel
Content-Type: application/json
{
  "id": 4,
  "name": "super 8",
  "address": "4233 hixon st",
  "rating": 5
}

###

@id=5
DELETE {{HotelListing_API_HostAddress}}/api/hotel/{{id}}

###

GET {{HotelListing_API_HostAddress}}/api/hotel/{{id}}

###

PUT {{HotelListing_API_HostAddress}}/api/hotel/{{id}}
Content-Type: application/json

{
  "name": "big 8",
  "address": "123 fake st",
  "rating": 4.6
}

###
